### ISSUE TITLE
Uncaught TypeError: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Chi-ne** [autopp/open-package#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [open-package](https://github.com/autopp/open-package) package 0.2.0

### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type undefined

```
At internal/validators.js:107

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:372:7)
    at PackageManager.resolvePackagePath (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:375734)
    at Object.didConfirmSelection (/packages/open-package/lib/open-package-view.js:59:43)
    at SelectListView.confirmSelection (/packages/open-package/node_modules/atom-select-list/src/select-list-view.js:242:18)
    at HTMLDivElement.coreConfirm (/packages/open-package/node_modules/atom-select-list/src/select-list-view.js:65:14)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:350265)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1230852)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1226986)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:284919)
```

### Commands

```
```

### Non-Core Packages

```
asciidoc-image-helper 1.0.1 
atom-beautify 0.33.4 
atom-browser 1.10.0 
atom-clock 0.1.18 
atom-image-resize 0.3.0 
atom-to-codepen 0.0.0 
bg-ui-font-sizer 2.0.0 
browse 3.2.0 
CodePress 0.3.0 
emmet 2.4.3 
emmet-simplified 2.6.0 
emmet-snippets-compatibility 1.0.6 
font-size-changer 2.0.0 
hugo-image 0.0.8 
ibm-cloud-developer-tools 0.1.2 
image-copipe 0.3.1 
imagemin 1.6.1 
latex-image-paste 0.5.0 
local-storage 0.12.3 
markdown-image-paste 2.5.2 
open-html-in-browser 0.2.1 
open-in-browser 0.5.2 
open-in-developer-mode 0.3.0 
open-package 0.2.0 
package-developer-toolbar 1.2.1 
platformio-ide-debugger 1.2.6 
reload-workspace-button 0.1.2 
satisfy-dependencies 0.4.3 
tool-bar 1.4.2 
Webfont 1.1.0 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by Chi-ne** [comment]
Do that later.
